# deploy hexo blog to aliyun oss
name: MainWorkflow
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 配置node环境
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          
      # 配置hexo环境,并build成html
      - name: Build Blog
        run: |
          npm i -g hexo-cli
          npm i
          hexo
          hexo generate
          
      # 配置oss环境
      - uses: manyuanrong/setup-ossutil@v1.0
        with:
         endpoint: "oss-cn-beijing.aliyuncs.com"
        # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
         access-key-id: ${{ secrets.ACCESS_KEY_ID }}
         access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          
     # 把生成好的html上传到oss
      - name: upload to oss
        run: |
          ossutil rm oss://aganblog/ -a -r -f
          ossutil cp pubilc oss://aganblog -r -f
